import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import { motion } from "framer-motion";
import { useRouter } from "next/router";

//components
import LayoutText from "../components/LayoutText";
import ArticleSkillsComponent from "@/components/ArticleSkillsComponent";
import ContainerLinkAnimated from "@/components/ContainerLinkAnimated";
import Footer from "@/components/Footer";

import { dataSkills } from "@/utils/skillsData";

import { articleSkills } from "@/models/typesIndex";

export default function Home({ mobilVersion }: { mobilVersion: boolean }) {
  const router = useRouter();

  return (
    <motion.main
      animate={{ y: "0%" }}
      exit={{ opacity: 1 }}
      initial={{ y: "100%" }}
      transition={{
        duration: 0.75,
        ease: "easeOut",
      }}
      className="text-gray-900 fixed top-0 left-0 w-full h-screen bg-primary-color overflow-y-auto"
    >
      <Head>
        <title>PortFolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" relative min-h-screen w-screen flex flex-col justify-center bg-primary-color font-Montserrat_regular  sm:px-16 lg:px-48  ">
        <div className="h-screen flex flex-col justify-between sm:justify-evenly">
          <div className="font-NotoSansGeorgian tracking-widest text-3xl w-full p-2 md:text-4xl  xl:w-3/5  ">
            <LayoutText delay={0.5} timeAnimation={0.02}>
              Hello, I'm Matthieu, a front-end developer specialized, with
              modern technologies built around the Javascript framework.
            </LayoutText>
          </div>

          <div className="min-w-full p-2  md:pl-20 xl:pl-80 text-2xl md:text-3xl">
            <LayoutText delay={1} timeAnimation={0.008}>
              As a front-end developer with expertise in React, Next.js, and
              TypeScript, I'm passionate about crafting user-friendly interfaces
              that bring ideas to life.
            </LayoutText>
          </div>

          <div className="mb-5 p-2 text-1xl md:text-3xl sm:mb-0">
            <LayoutText delay={1.2} timeAnimation={0.005}>
              What i can bring to you:
            </LayoutText>
          </div>
        </div>

        {dataSkills?.map((skill: articleSkills, index) => {
          return (
            <ArticleSkillsComponent
              key={index}
              title={skill.title}
              image={skill.image}
              text={skill.text}
              mobilVersion={mobilVersion}
            />
          );
        })}

        <div className="mt-14 mb-14">
          <h3 className=" mb-8  tracking-widest text-4xl uppercase text-center ">
            Current Focus
          </h3>
          <h4 className="leading-6 p-2 md:leading-10 m-2 text-1xl 2xl:text-2xl">
            working on improving my skills in Continuous Integration and \
            Deployment (CI/CD) by learning Docker and how to use it to create
            and \ manage containers for various applications.
          </h4>
          <h4 className="leading-6 p-2 md:leading-10 m-2 text-1xl 2xl:text-2xl">
            Unit testing with the Jest library.
          </h4>
        </div>

        <div className="mt-20">
          <ContainerLinkAnimated
            title={"Projects / works"}
            linkImage={"/homeMin.png"}
            index={1}
          />
          <ContainerLinkAnimated
            title={"Contact"}
            linkImage={"/homeMin.png"}
            index={2}
          />
        </div>
        <Footer />
      </main>
    </motion.main>
  );
}
